import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    proxy: {
      '/list-pdfs': 'http://localhost:5000',
      '/api/delete-all-notification-history': 'http://localhost:5000',
      '/view-pdf': 'http://localhost:5000',
      '/download-pdf': 'http://localhost:5000',
      "/pdf-cover": "http://localhost:5000",
      '/authorize': 'http://localhost:5000',
      '/api/pdf-text': 'http://localhost:5000',
      '/api/register': 'http://localhost:5000',
      '/api/login': 'http://localhost:5000',
      '/api/update-colors': 'http://localhost:5000',
      '/api/update-profile-settings': 'http://localhost:5000',
      '/api/update-external-id': 'http://localhost:5000',
      '/api/change-password': 'http://localhost:5000',
      '/api/add-secondary-email': 'http://localhost:5000',
      '/api/remove-secondary-email': 'http://localhost:5000',
      '/api/notification-prefs': 'http://localhost:5000',
      '/api/notification-history': 'http://localhost:5000',
      '/api/seed-notifications': 'http://localhost:5000',
      '/api/notify-new-book': 'http://localhost:5000',
      '/api/notify-book-update': 'http://localhost:5000',
      '/api/notify-app-update': 'http://localhost:5000',
      '/api/add-bookmark': 'http://localhost:5000',
      '/api/remove-bookmark': 'http://localhost:5000',
      '/api/get-bookmarks': 'http://localhost:5000',
      '/api/update-bookmark-meta': 'http://localhost:5000',
      '/api/get-user': 'http://localhost:5000',
      '/api/get-user-meta': 'http://localhost:5000',
      '/api/vote-book': 'http://localhost:5000',
      '/api/book-votes': 'http://localhost:5000',
      '/api/top-voted-books': 'http://localhost:5000',
      '/api/user-voted-books': 'http://localhost:5000',
      '/api/test-send-scheduled-notifications': 'http://localhost:5000',
      '/api/get-notification-prefs': 'http://localhost:5000',
      '/api/update-notification-prefs': 'http://localhost:5000',
      '/api/get-notification-history': 'http://localhost:5000',
      '/api/delete-notification': 'http://localhost:5000',
      '/api/delete-notification-history': 'http://localhost:5000',
      '/api/mark-notification-read': 'http://localhost:5000',
      '/api/dismiss-all-notifications': 'http://localhost:5000',
      '/api/mark-all-notifications-read': 'http://localhost:5000',
      '/api/delete-comment': 'http://localhost:5000',
      '/api/delete-account': 'http://localhost:5000',
      '/api/get-comments': 'http://localhost:5000',
      '/api/vote-comment': 'http://localhost:5000',
      '/api/get-comment-votes': 'http://localhost:5000',
      '/api/user-comments': 'http://localhost:5000',
      '/api/moderate-comment': 'http://localhost:5000',
      '/api/mark-notifications-read': 'http://localhost:5000',
      '/api/dismiss-notification': 'http://localhost:5000',
      '/api/admin/send-emergency-email': 'http://localhost:5000',
      '/api/admin/make-admin': 'http://localhost:5000',
      '/api/all-books': 'http://localhost:5000',
    }
  }
})
